Repository NikolaySavenko/domus-sapiens, pull requests merged in 2021-10, with the labels that each got.

#14 docs(design): add figma links to readme - #13
  README.md
Labels: documentation

#22 feat: add frontend service template - #17
  .gitignore
  DomusSapiensBackend/.dockerignore
  DomusSapiensBackend/DomusSapiensBackend.sln
  DomusSapiensBackend/FrontendService/Controllers/WeatherForecastController.cs
  DomusSapiensBackend/FrontendService/Dockerfile
  DomusSapiensBackend/FrontendService/FrontendService.csproj
  DomusSapiensBackend/FrontendService/Program.cs
  DomusSapiensBackend/FrontendService/Properties/launchSettings.json
  DomusSapiensBackend/FrontendService/WeatherForecast.cs
  DomusSapiensBackend/FrontendService/appsettings.Development.json
  DomusSapiensBackend/FrontendService/appsettings.json
Labels: backend

#31 feat(design): add link to figma
  README.md
Labels: design

#62 feat(design): add link to Logo - #54
  README.md
Labels: design

#59 fix(compose): forward service ports and setup services env - #55
  docker-compose.yml
Labels: documentation, design, backend, automatization

#63 docs(architecture): add diagram for app v1 - #33
  Architecture/domus-sapiensV1.drawio
  Architecture/domus-sapiensV1.png
  Architecture/domus-sapiensV1.svg
Labels: documentation, design
