Repository NikolaySavenko/domus-sapiens, pull requests merged in 2021-12, with the labels that each got.

#119 feat(architecture scheme): improved architecture scheme - #86
  Architecture/New_scheme.drawio.svg
  Architecture/New_scheme.png
  Architecture/improved-architecture-scheme.drawio
Labels: documentation, design

#121 fix(quasar): fix bug with button
  Frontend/src/components/CompositionComponent.vue
  Frontend/src/pages/index.vue
  Frontend/src/pages/information.vue
Labels: bug, documentation

#124 fix: correct send json - #123
  DomusSapiensBackend/IoTControlService/Model/Command/CommandFactory.cs
  DomusSapiensBackend/IoTControlService/Model/DeviceMethods/GPIOSwitch.cs
  DomusSapiensBackend/IoTControlService/Model/DeviceMethods/IDeviceMethod.cs
Labels: bug, backend
